# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

r_github_packages:
    - r-lib/covr

matrix:
  include:
  - r: devel
  - r: release
  - r: oldrel
  - r: 3.5

matrix:
    include:
        compiler: clang

notifications:
    email:
        on_success: change
        on_failure: change

after_success:
    - Rscript -e 'covr::codecov()'

CODECOV_TOKEN = 09b54ea9-a049-4ff4-8e1c-25649392594c
